apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: managed-cluster
  region: eu-west-1
managedNodeGroups:
  - name: nodos1
    minSize: 2
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 20
    labels: {project: web}
    tags:
      project: web
