apiVersion: v1
kind: Service
metadata:
  name: servicio-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: nginx
    environment: testing-loadbalancer
  ports:
    - protocol: TCP
      port: 80
