apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: servicio1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        servicio: servicio1
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: servicio1
spec:
  type: ClusterIP
  selector:
    app: nginx
    servicio: servicio1
  ports:
    - protocol: TCP
      port: 80
