apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-testing-loadbalancer-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: testing-loadbalancer-tls
  template:
    metadata:
      labels:
        app: nginx
        environment: testing-loadbalancer-tls
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
