apiVersion: v1
kind: Service
metadata:
  name: servicio-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:eu-west-1:972777588758:certificate/d91b42b0-fd71-43eb-8905-cde17a212fc4
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: LoadBalancer
  selector:
    app: nginx
    environment: testing-loadbalancer-tls
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
