apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-001
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-volume-001"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-volume-claim-1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: servicio1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        servicio: servicio1
    spec:
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: pv-volume-claim-1

      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-storage
---
apiVersion: v1
kind: Service
metadata:
  name: servicio1
spec:
  type: ClusterIP
  selector:
    app: nginx
    servicio: servicio1
  ports:
    - protocol: TCP
      port: 80
