apiVersion: v1
kind: Pod
metadata:
  name: web-affinity-az
  namespace: pod-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - eu-west-1b
            - eu-west-1a
  containers:
  - name: web
    image: nginx:latest

