apiVersion: v1
kind: Pod
metadata:
  name: nginx-limits-no-restart
spec:
  restartPolicy: Never
  containers:
  - name: webserver
    image: nginx:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
